# Generated by Django 5.0 on 2024-03-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('RIDER', 'Rider'), ('CUSTOMER', 'Customer')], default='Customer', max_length=50, null=True),
        ),
    ]
