# Generated by Django 5.0 on 2024-03-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('RIDER', 'Rider'), ('CUSTOMER', 'Customer')], default='Customer', max_length=50, null=True),
        ),
    ]
